import React from 'react';
import { FileText, Printer, Download, CheckCircle2, ShieldAlert, DollarSign, TrendingUp, HardDrive } from 'lucide-react';
import { OperationalPlan } from '../api/types';
import { Card } from '../components/ui/Card';
import { StatCard } from '../components/ui/StatCard';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';

interface ActionPlanProps {
  plan: OperationalPlan;
}

export const ActionPlan: React.FC<ActionPlanProps> = ({ plan }) => {
  const { summary, recommendations, allocation_plan, risk_plan } = plan;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6 pb-12 print:p-0">
      {/* Header & Print Control */}
      <div className="bg-white p-4 rounded-xl border border-slate-200/80 shadow-sm flex items-center justify-between print:hidden">
        <div>
          <h1 className="text-lg font-bold text-slate-900 flex items-center gap-2">
            <FileText className="w-5 h-5 text-teal-700" />
            Executive Operational Action Plan
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Master decision report for management deployment & plant operations
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={handlePrint} icon={<Printer className="w-3.5 h-3.5" />}>
            Print / Export PDF
          </Button>
        </div>
      </div>

      {/* Report Document Box */}
      <div className="tower-card p-6 space-y-6 bg-white border border-slate-200">
        {/* Document Header */}
        <div className="border-b border-slate-200 pb-4 flex justify-between items-start">
          <div>
            <span className="text-[10px] font-bold uppercase tracking-widest text-teal-700">
              BioKraft Foods — Operational Intelligence Report
            </span>
            <h2 className="text-xl font-bold font-display text-slate-900 mt-0.5">
              Target Horizon Plan: {plan.target_period}
            </h2>
            <div className="text-xs text-slate-500 mt-1 flex items-center gap-3">
              <span>Strategy: <strong className="text-slate-800 uppercase">{plan.strategy}</strong></span>
              <span>•</span>
              <span>Risk Mode: <strong className="text-slate-800 uppercase">{plan.risk_mode}</strong></span>
            </div>
          </div>

          <div className="text-right">
            <Badge variant={summary.shortage_kg > 0 ? 'danger' : 'success'} size="md">
              {summary.risk_level} RISK LEVEL
            </Badge>
            <div className="text-[11px] text-slate-400 mt-1">Generated by Engine Core</div>
          </div>
        </div>

        {/* Master Metrics Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="p-3 bg-slate-50 border border-slate-200/80 rounded-lg">
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Total Forecast Demand</span>
            <div className="text-xl font-bold text-slate-900 font-display mt-1">{summary.forecast_demand_kg.toLocaleString()} kg</div>
            <span className="text-[11px] text-slate-500">B2B: {summary.b2b_demand_kg} kg | D2C: {summary.d2c_demand_kg} kg</span>
          </div>

          <div className="p-3 bg-slate-50 border border-slate-200/80 rounded-lg">
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Usable Plant Capacity</span>
            <div className="text-xl font-bold text-slate-900 font-display mt-1">{summary.usable_capacity_kg.toLocaleString()} kg</div>
            <span className="text-[11px] text-slate-500">Internal + Co-Mfg</span>
          </div>

          <div className="p-3 bg-slate-50 border border-slate-200/80 rounded-lg">
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Projected Shortage Gap</span>
            <div className="text-xl font-bold text-rose-600 font-display mt-1">{summary.shortage_kg.toLocaleString()} kg</div>
            <span className="text-[11px] text-rose-600 font-semibold">{summary.shortage_kg > 0 ? 'Capacity Shortfall' : 'Fully Satisfied'}</span>
          </div>

          <div className="p-3 bg-slate-50 border border-slate-200/80 rounded-lg">
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Projected Revenue</span>
            <div className="text-xl font-bold text-emerald-700 font-display mt-1">₹{(summary.projected_revenue_inr / 100000).toFixed(2)}L</div>
            <span className="text-[11px] text-slate-500">Fulfillment: {summary.fulfillment_pct.toFixed(1)}%</span>
          </div>
        </div>

        {/* Priority Action Items */}
        <div className="space-y-3">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 flex items-center gap-1.5">
            <CheckCircle2 className="w-4 h-4 text-teal-700" /> Mandated Mitigation Actions
          </h3>
          <div className="space-y-2">
            {recommendations.map((rec, idx) => (
              <div key={idx} className="p-3.5 bg-slate-50 border border-slate-200/80 rounded-lg space-y-1">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Badge variant={rec.priority === 'HIGH' ? 'danger' : rec.priority === 'MEDIUM' ? 'warning' : 'info'} size="sm">
                      {rec.priority}
                    </Badge>
                    <h4 className="text-xs font-bold text-slate-900">{rec.title}</h4>
                  </div>
                  {rec.estimated_impact && (
                    <Badge variant="teal" size="sm" className="font-semibold">
                      {rec.estimated_impact}
                    </Badge>
                  )}
                </div>
                <p className="text-xs text-slate-600 leading-relaxed">{rec.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Allocation Summary Table */}
        <div className="space-y-3">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900">
            Segment Capacity Allocation Summary
          </h3>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-slate-200 bg-slate-50 text-slate-500 font-semibold">
                  <th className="py-2 px-3">Segment</th>
                  <th className="py-2 px-3">Region</th>
                  <th className="py-2 px-3">Channel</th>
                  <th className="py-2 px-3 text-right">Demand (kg)</th>
                  <th className="py-2 px-3 text-right">Allocated (kg)</th>
                  <th className="py-2 px-3 text-right">Fulfillment</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {(allocation_plan.segments || []).map((seg) => (
                  <tr key={seg.segment_id}>
                    <td className="py-2 px-3 font-mono font-bold text-slate-900">{seg.segment_id}</td>
                    <td className="py-2 px-3">{seg.region}</td>
                    <td className="py-2 px-3">{seg.channel}</td>
                    <td className="py-2 px-3 text-right">{seg.demand_kg.toLocaleString()}</td>
                    <td className="py-2 px-3 text-right font-bold text-teal-700">{seg.allocated_kg.toLocaleString()}</td>
                    <td className="py-2 px-3 text-right font-semibold">{seg.fulfillment_pct.toFixed(1)}%</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};
