import React from 'react';
import { Layers, Sliders, CheckCircle2, AlertTriangle, Shield, HelpCircle } from 'lucide-react';
import { OperationalPlan, OptimizationStrategy } from '../api/types';
import { Card } from '../components/ui/Card';
import { StatCard } from '../components/ui/StatCard';
import { Badge } from '../components/ui/Badge';

interface AllocationProps {
  plan: OperationalPlan;
  onSelectStrategy: (strategy: OptimizationStrategy) => void;
  isUpdatingStrategy?: boolean;
}

export const Allocation: React.FC<AllocationProps> = ({
  plan,
  onSelectStrategy,
  isUpdatingStrategy = false,
}) => {
  const { summary, allocation_plan } = plan;
  const segments = allocation_plan.segments || [];

  return (
    <div className="space-y-8 pb-12 font-sans max-w-7xl mx-auto">
      {/* Editorial Header & Policy Switcher */}
      <div className="bg-white border border-[#DEDED8] rounded-[2px] p-8 space-y-6">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div className="space-y-2">
            <div className="text-[11px] font-bold tracking-widest text-[#64645F] uppercase font-mono">
              02 / ALLOCATION OPTIMIZER
            </div>
            <h1 className="text-3xl lg:text-4xl font-bold text-[#111111] tracking-tight">
              Capacity allocated by priority.
            </h1>
            <p className="text-sm text-[#64645F] max-w-xl">
              Linear Programming optimization solver (Google OR-Tools GLOP) partitioning available production capacity across demand channels.
            </p>
          </div>

          {/* Minimal Strategy Switcher */}
          <div className="flex items-center gap-2 bg-[#F7F7F2] p-2 border border-[#DEDED8] rounded-[2px] shrink-0">
            <Sliders className="w-3.5 h-3.5 text-[#64645F]" />
            <span className="text-[10px] font-bold uppercase tracking-wider text-[#64645F] mr-1">Policy:</span>
            {(
              [
                { id: 'balanced', label: 'Balanced' },
                { id: 'revenue', label: 'Max Revenue' },
                { id: 'fulfillment', label: 'Max Fulfillment' },
              ] as const
            ).map((item) => (
              <button
                key={item.id}
                disabled={isUpdatingStrategy}
                onClick={() => onSelectStrategy(item.id)}
                className={`px-3 py-1 text-xs font-bold uppercase tracking-wider rounded-[2px] transition-all cursor-pointer ${
                  plan.strategy === item.id
                    ? 'bg-[#324C3A] text-white'
                    : 'text-[#64645F] hover:text-[#111111] hover:bg-[#DEDED8]/40'
                }`}
              >
                {item.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Metric Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4">
        <StatCard
          title="Available Capacity"
          value={allocation_plan.available_capacity_kg}
          unit="kg"
          subtitle="Solver Hard Constraint"
        />
        <StatCard
          title="Total Demand"
          value={allocation_plan.total_demand_kg}
          unit="kg"
          subtitle="Requested Volume"
        />
        <StatCard
          title="Allocated Capacity"
          value={allocation_plan.allocated_capacity_kg}
          unit="kg"
          subtitle={`${allocation_plan.utilization_pct.toFixed(0)}% Utilized`}
          badgeText="Optimized"
          badgeVariant="success"
        />
        <StatCard
          title="Unfulfilled Shortage"
          value={allocation_plan.unfulfilled_demand_kg}
          unit="kg"
          subtitle="Production Deficit"
          badgeText={allocation_plan.unfulfilled_demand_kg > 0 ? 'Shortage' : 'Satisfied'}
          badgeVariant={allocation_plan.unfulfilled_demand_kg > 0 ? 'danger' : 'success'}
        />
        <StatCard
          title="B2B SLA Fulfillment"
          value={`${allocation_plan.b2b_fulfillment_pct.toFixed(1)}%`}
          subtitle="Contractual Commitment"
          badgeText="Protected"
          badgeVariant="teal"
        />
        <StatCard
          title="D2C Fulfillment"
          value={`${allocation_plan.d2c_fulfillment_pct.toFixed(1)}%`}
          subtitle="Consumer Retail"
          badgeText="Retail"
          badgeVariant="info"
        />
      </div>

      {/* Visual Segment Allocation Progress */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card
          title="Segment-Level Capacity Allocation"
          subtitle="Individual channel allocation breakdown generated by OR-Tools LP Optimizer"
          className="lg:col-span-2"
        >
          <div className="space-y-4 pt-2 font-sans">
            {segments.map((seg) => {
              const ful = seg.fulfillment_pct;
              const isFull = ful >= 99.9;
              const isLow = ful < 60;

              return (
                <div key={seg.segment_id} className="p-4 bg-[#F7F7F2] border border-[#DEDED8] rounded-[2px] space-y-2.5">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
                    <div className="flex items-center gap-2">
                      <span className="font-mono font-bold text-[#111111]">{seg.segment_id}</span>
                      <span className="text-[#64645F] font-medium">({seg.region} — {seg.channel})</span>
                      <Badge variant={seg.channel === 'B2B' ? 'teal' : 'info'} size="sm">
                        {seg.channel}
                      </Badge>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-[#64645F] text-[11px]">
                        Demand: <strong className="text-[#111111] font-mono">{(seg.demand_kg ?? seg.forecast_demand_kg ?? 0).toLocaleString()} kg</strong>
                      </span>
                      <span className="text-[#64645F] text-[11px]">
                        Allocated: <strong className="text-[#324C3A] font-mono">{(seg.allocated_kg ?? 0).toLocaleString()} kg</strong>
                      </span>
                      <Badge variant={isFull ? 'success' : isLow ? 'danger' : 'warning'} size="sm">
                        {ful.toFixed(1)}% Fulfilled
                      </Badge>
                    </div>
                  </div>

                  {/* Progress Meter */}
                  <div className="w-full bg-[#DEDED8] h-2 rounded-[2px] overflow-hidden flex">
                    <div
                      className={`h-full transition-all duration-500 rounded-[2px] ${
                        isFull ? 'bg-[#324C3A]' : isLow ? 'bg-[#9E3B3B]' : 'bg-[#718B6B]'
                      }`}
                      style={{ width: `${Math.min(ful, 100)}%` }}
                    />
                  </div>

                  {/* Unfulfilled gap warning */}
                  {seg.unfulfilled_kg > 0 && (
                    <div className="text-[11px] text-[#9E3B3B] font-mono font-semibold flex items-center gap-1">
                      <AlertTriangle className="w-3 h-3" /> Unfulfilled Deficit: {seg.unfulfilled_kg.toLocaleString()} kg
                      (₹{((seg.revenue_inr / seg.allocated_kg) * seg.unfulfilled_kg || 0).toLocaleString('en-IN')} unrealized revenue)
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </Card>

        {/* Solver Logic Explanation */}
        <Card
          title="Optimization Rationale"
          subtitle="Deterministic linear programming solver logic explanations"
        >
          <div className="space-y-4 font-sans">
            <div className="p-4 bg-[#324C3A] text-white rounded-[2px] space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold tracking-wider uppercase text-white/90 font-mono">
                <Shield className="w-4 h-4 text-white" /> Active Policy: {allocation_plan.strategy.toUpperCase()}
              </div>
              <p className="text-xs text-white/80 leading-relaxed">
                Available capacity ({allocation_plan.available_capacity_kg.toLocaleString()} kg) is constrained. Penalty parameters enforce B2B contractual SLAs at 10x penalty weight relative to unfulfilled D2C retail demand.
              </p>
            </div>

            <div className="space-y-3 pt-1">
              <h4 className="text-xs font-bold text-[#111111] uppercase tracking-wider">
                Solver Logic Rationale
              </h4>
              {(allocation_plan.explanations || []).map((exp, idx) => (
                <div key={idx} className="p-3 bg-[#F7F7F2] border border-[#DEDED8] rounded-[2px] flex items-start gap-2.5 text-xs text-[#111111] leading-relaxed">
                  <CheckCircle2 className="w-4 h-4 text-[#324C3A] shrink-0 mt-0.5" />
                  <div>{exp}</div>
                </div>
              ))}
            </div>

            <div className="p-3 bg-[#F7F7F2] border border-[#DEDED8] rounded-[2px] text-xs space-y-1">
              <span className="font-bold text-[#111111] flex items-center gap-1 uppercase text-[10px] tracking-wider">
                <HelpCircle className="w-3.5 h-3.5 text-[#64645F]" /> Shortage Slack Variable Formulation
              </span>
              <p className="text-[#64645F] text-[11px] leading-relaxed">
                The Google OR-Tools LP formulation guarantees solver convergence when commitments exceed usable capacity by evaluating continuous slack variables: <code>allocation_i + shortfall_i &gt;= min_contract_i</code>.
              </p>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
};

