import React from 'react';
import { Layers, Sliders, CheckCircle2, AlertTriangle, Shield, HelpCircle, ArrowRight } from 'lucide-react';
import { OperationalPlan, OptimizationStrategy, SegmentAllocation } from '../api/types';
import { Card } from '../components/ui/Card';
import { StatCard } from '../components/ui/StatCard';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  Legend, Cell
} from 'recharts';

interface AllocationProps {
  plan: OperationalPlan;
  onSelectStrategy: (strategy: OptimizationStrategy) => void;
  isUpdatingStrategy?: boolean;
}

export const Allocation: React.FC<AllocationProps> = ({
  plan,
  onSelectStrategy,
  isUpdatingStrategy = false,
}) => {
  const { summary, allocation_plan } = plan;
  const segments = allocation_plan.segments || [];

  return (
    <div className="space-y-6 pb-12">
      {/* Strategy Switcher Bar */}
      <div className="bg-white p-4 rounded-xl border border-slate-200/80 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-lg font-bold text-slate-900 flex items-center gap-2">
            <Layers className="w-5 h-5 text-teal-700" />
            Constrained Capacity Allocation
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Linear Programming optimization solver (Google OR-Tools GLOP) allocating available capacity
          </p>
        </div>

        {/* Strategy Selector Pills */}
        <div className="flex items-center gap-1.5 bg-slate-100 p-1 rounded-lg border border-slate-200">
          <Sliders className="w-3.5 h-3.5 text-slate-500 ml-2" />
          <span className="text-xs text-slate-500 font-medium mr-1">Policy:</span>
          {(
            [
              { id: 'balanced', label: 'Balanced Policy' },
              { id: 'revenue', label: 'Max Revenue' },
              { id: 'fulfillment', label: 'Max Fulfillment' },
            ] as const
          ).map((item) => (
            <button
              key={item.id}
              disabled={isUpdatingStrategy}
              onClick={() => onSelectStrategy(item.id)}
              className={`px-3 py-1.5 rounded-md text-xs font-semibold transition-all cursor-pointer ${
                plan.strategy === item.id
                  ? 'bg-teal-700 text-white shadow-sm'
                  : 'text-slate-600 hover:text-slate-900 hover:bg-slate-200/60'
              }`}
            >
              {item.label}
            </button>
          ))}
        </div>
      </div>

      {/* Metric Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4">
        <StatCard
          title="Available Capacity"
          value={allocation_plan.available_capacity_kg}
          unit="kg"
          subtitle="Solver Constraint"
          icon={<Layers className="w-4 h-4 text-teal-700" />}
        />
        <StatCard
          title="Total Demand"
          value={allocation_plan.total_demand_kg}
          unit="kg"
          subtitle="Requested Volume"
        />
        <StatCard
          title="Allocated Capacity"
          value={allocation_plan.allocated_capacity_kg}
          unit="kg"
          subtitle={`${allocation_plan.utilization_pct.toFixed(0)}% Utilized`}
          badgeText="Optimized"
          badgeVariant="success"
        />
        <StatCard
          title="Unfulfilled Shortage"
          value={allocation_plan.unfulfilled_demand_kg}
          unit="kg"
          subtitle="Capacity Shortfall"
          badgeText={allocation_plan.unfulfilled_demand_kg > 0 ? 'Shortage' : 'Satisfied'}
          badgeVariant={allocation_plan.unfulfilled_demand_kg > 0 ? 'danger' : 'success'}
        />
        <StatCard
          title="B2B SLA Fulfillment"
          value={`${allocation_plan.b2b_fulfillment_pct.toFixed(1)}%`}
          subtitle="Contract Protection"
          badgeText="Priority SLA"
          badgeVariant="teal"
        />
        <StatCard
          title="D2C Fulfillment"
          value={`${allocation_plan.d2c_fulfillment_pct.toFixed(1)}%`}
          subtitle="Consumer Retail"
          badgeText="Retail Supply"
          badgeVariant="info"
        />
      </div>

      {/* Visual Segment Fulfillment Bars */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card
          title="Demand vs Allocated Capacity by Segment"
          subtitle="Individual channel allocation breakdown generated by OR-Tools LP Optimizer"
          className="lg:col-span-2"
        >
          <div className="space-y-4 pt-2">
            {segments.map((seg) => {
              const ful = seg.fulfillment_pct;
              const isFull = ful >= 99.9;
              const isLow = ful < 60;

              return (
                <div key={seg.segment_id} className="p-3.5 bg-slate-50 border border-slate-200/80 rounded-lg space-y-2">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1 text-xs">
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-slate-900 font-mono">{seg.segment_id}</span>
                      <span className="text-slate-600 font-medium">({seg.region} — {seg.channel})</span>
                      <Badge variant={seg.channel === 'B2B' ? 'teal' : 'info'} size="sm">
                        {seg.channel}
                      </Badge>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-slate-600">
                        Demand: <strong className="text-slate-900">{(seg.demand_kg ?? seg.forecast_demand_kg ?? 0).toLocaleString()} kg</strong>
                      </span>
                      <span className="text-slate-600">
                        Allocated: <strong className="text-teal-700">{(seg.allocated_kg ?? 0).toLocaleString()} kg</strong>
                      </span>
                      <Badge variant={isFull ? 'success' : isLow ? 'danger' : 'warning'} size="sm">
                        {ful.toFixed(1)}% Fulfilled
                      </Badge>
                    </div>
                  </div>

                  {/* Progress Bar */}
                  <div className="w-full bg-slate-200 h-2.5 rounded-full overflow-hidden flex">
                    <div
                      className={`h-full transition-all duration-500 rounded-full ${
                        isFull ? 'bg-emerald-500' : isLow ? 'bg-rose-500' : 'bg-teal-600'
                      }`}
                      style={{ width: `${Math.min(ful, 100)}%` }}
                    />
                  </div>

                  {/* Unfulfilled gap subtext */}
                  {seg.unfulfilled_kg > 0 && (
                    <div className="text-[11px] text-rose-600 font-medium flex items-center gap-1">
                      <AlertTriangle className="w-3 h-3" /> Unfulfilled Deficit: {seg.unfulfilled_kg.toLocaleString()} kg
                      (₹{((seg.revenue_inr / seg.allocated_kg) * seg.unfulfilled_kg || 0).toLocaleString('en-IN')} unrealized revenue)
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </Card>

        {/* Deterministic Optimizer Explanations */}
        <Card
          title="Why This Allocation?"
          subtitle="Deterministic linear programming explanations from optimizer solver constraints"
        >
          <div className="space-y-4">
            <div className="p-3.5 bg-teal-900 text-white rounded-lg space-y-2">
              <div className="flex items-center gap-2 text-xs font-bold text-teal-200">
                <Shield className="w-4 h-4 text-teal-300" /> Current Policy: {allocation_plan.strategy.toUpperCase()}
              </div>
              <p className="text-xs text-teal-100/90 leading-relaxed">
                Available capacity ({allocation_plan.available_capacity_kg.toLocaleString()} kg) is constrained. Shortfall slack variables penalize B2B contractual breaches at 10x standard penalty weight.
              </p>
            </div>

            <div className="space-y-3 pt-1">
              <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wider text-slate-500">
                Solver Logic Rationale
              </h4>
              {(allocation_plan.explanations || []).map((exp, idx) => (
                <div key={idx} className="p-3 bg-slate-50 border border-slate-200/80 rounded-lg flex items-start gap-2.5 text-xs text-slate-700 leading-relaxed">
                  <CheckCircle2 className="w-4 h-4 text-teal-700 shrink-0 mt-0.5" />
                  <div>{exp}</div>
                </div>
              ))}
            </div>

            <div className="p-3 bg-slate-100 border border-slate-200 rounded-lg text-xs space-y-1">
              <span className="font-semibold text-slate-800 flex items-center gap-1">
                <HelpCircle className="w-3.5 h-3.5 text-slate-500" /> Shortage Slack Variable Protection
              </span>
              <p className="text-slate-600 text-[11px] leading-relaxed">
                The OR-Tools LP formulation prevents model infeasibility when commitments exceed available capacity by utilizing slack variables: <code>allocation_i + shortfall_i &gt;= minimum_commitment_i</code>.
              </p>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
};
