import React from 'react';
import { Target, AlertTriangle, DollarSign } from 'lucide-react';
import { OperationalPlan, MarketingAction } from '../api/types';
import { Card } from '../components/ui/Card';
import { StatCard } from '../components/ui/StatCard';
import { Badge } from '../components/ui/Badge';

interface MarketingProps {
  plan: OperationalPlan;
}

export const Marketing: React.FC<MarketingProps> = ({ plan }) => {
  const { marketing_recommendations } = plan;
  const recommendations: MarketingAction[] = marketing_recommendations?.recommendations || [];

  return (
    <div className="space-y-8 pb-12 font-sans max-w-7xl mx-auto">
      {/* Editorial Header */}
      <div className="bg-white border border-[#DEDED8] rounded-[2px] p-8 space-y-4">
        <div className="text-[11px] font-bold tracking-widest text-[#64645F] uppercase font-mono">
          05 / MARKETING INTELLIGENCE
        </div>
        <h1 className="text-3xl lg:text-4xl font-bold text-[#111111] tracking-tight">
          Capacity-aware demand acquisition.
        </h1>
        <p className="text-sm text-[#64645F] max-w-xl">
          Harmonizing regional marketing campaign spend with real-time manufacturing capacity constraints to prevent demand overhang.
        </p>
      </div>

      {/* Critical UX Principle Warning Banner */}
      <div className="bg-[#324C3A] text-white p-6 rounded-[2px] border border-[#324C3A] flex items-start gap-4 shadow-sm font-sans">
        <AlertTriangle className="w-5 h-5 text-white shrink-0 mt-0.5" />
        <div className="space-y-1">
          <div className="text-xs font-bold uppercase tracking-wider font-mono text-white/90">
            Core Operational Rule: High Marketing ROAS ≠ Automatic Spend Increase
          </div>
          <p className="text-xs text-white/80 leading-relaxed">
            When manufacturing plant capacity is bottlenecked, escalating demand generation spend creates unfulfillable customer orders, resulting in wasted ad budget, lost revenue, and brand damage.
          </p>
        </div>
      </div>

      {/* Summary KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <StatCard
          title="Total Marketing Spend"
          value={`₹${((marketing_recommendations?.summary?.total_spend_inr || 148000) / 1000).toFixed(0)}k`}
          subtitle="Current Q2 Acquisition Budget"
        />
        <StatCard
          title="Recommended Spend"
          value={`₹${((marketing_recommendations?.summary?.total_recommended_spend_inr || 125000) / 1000).toFixed(0)}k`}
          subtitle="Capacity-Optimized Budget"
          badgeText="Optimized"
          badgeVariant="teal"
        />
        <StatCard
          title="Constrained Campaigns"
          value={marketing_recommendations?.summary?.constrained_campaigns_count || 3}
          subtitle="Bottlenecked by Plant Limits"
          badgeText="Bottlenecked"
          badgeVariant="warning"
        />
      </div>

      {/* Marketing Action Cards */}
      <Card
        title="REGIONAL CAMPAIGN REALLOCATION DIRECTIVES"
        subtitle="Capacity-aware budget recommendations generated by the optimizer engine"
      >
        <div className="space-y-4 pt-2 font-sans">
          {recommendations.map((item, idx) => {
            const isHold = item.action === 'HOLD';
            const isReduce = item.action === 'REDUCE' || item.action === 'REALLOCATE_OUT';

            return (
              <div
                key={idx}
                className="p-5 bg-[#F7F7F2] border border-[#DEDED8] rounded-[2px] space-y-3"
              >
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                  <div className="flex items-center gap-3">
                    <h3 className="text-xs font-bold text-[#111111] uppercase tracking-wider font-mono">
                      {item.region} — {item.channel}
                    </h3>
                    <Badge
                      variant={isReduce ? 'danger' : isHold ? 'warning' : 'success'}
                      size="sm"
                    >
                      {item.action.replace('_', ' ')}
                    </Badge>
                  </div>

                  <div className="flex items-center gap-4 text-xs font-mono">
                    <span className="text-[#64645F]">
                      ROAS: <strong className="text-[#111111]">{item.roas}x</strong>
                    </span>
                    <span className="text-[#64645F]">
                      Fulfillment: <strong className={item.fulfillment_pct < 60 ? 'text-[#9E3B3B]' : 'text-[#324C3A]'}>{item.fulfillment_pct.toFixed(1)}%</strong>
                    </span>
                  </div>
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 p-3 bg-white border border-[#DEDED8] rounded-[2px] text-xs font-mono">
                  <div>
                    <span className="text-[#64645F] text-[9px] uppercase font-bold tracking-wider block font-sans">Current Spend</span>
                    <span className="font-bold text-[#111111]">₹{item.current_spend_inr.toLocaleString('en-IN')}</span>
                  </div>
                  <div>
                    <span className="text-[#64645F] text-[9px] uppercase font-bold tracking-wider block font-sans">Recommended</span>
                    <span className="font-bold text-[#324C3A]">₹{item.recommended_spend_inr.toLocaleString('en-IN')}</span>
                  </div>
                  <div>
                    <span className="text-[#64645F] text-[9px] uppercase font-bold tracking-wider block font-sans">Efficiency</span>
                    <span className="font-bold text-[#111111]">{item.demand_efficiency} kg / ₹1k</span>
                  </div>
                  <div>
                    <span className="text-[#64645F] text-[9px] uppercase font-bold tracking-wider block font-sans">Budget Change</span>
                    <span className={`font-bold ${item.recommended_spend_inr < item.current_spend_inr ? 'text-[#9E3B3B]' : 'text-[#324C3A]'}`}>
                      {item.recommended_spend_inr - item.current_spend_inr === 0
                        ? '₹0'
                        : `₹${(item.recommended_spend_inr - item.current_spend_inr).toLocaleString('en-IN')}`}
                    </span>
                  </div>
                </div>

                <p className="text-xs text-[#64645F] leading-relaxed italic bg-white p-3 rounded-[2px] border border-[#DEDED8] font-sans">
                  {item.reason}
                </p>
              </div>
            );
          })}
        </div>
      </Card>
    </div>
  );
};

