import React from 'react';
import { Target, AlertTriangle, TrendingUp, DollarSign, ArrowRight, ShieldAlert, CheckCircle2 } from 'lucide-react';
import { OperationalPlan, MarketingAction } from '../api/types';
import { Card } from '../components/ui/Card';
import { StatCard } from '../components/ui/StatCard';
import { Badge } from '../components/ui/Badge';

interface MarketingProps {
  plan: OperationalPlan;
}

export const Marketing: React.FC<MarketingProps> = ({ plan }) => {
  const { marketing_recommendations, summary } = plan;
  const recommendations: MarketingAction[] = marketing_recommendations?.recommendations || [];

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="bg-white p-4 rounded-xl border border-slate-200/80 shadow-sm">
        <h1 className="text-lg font-bold text-slate-900 flex items-center gap-2">
          <Target className="w-5 h-5 text-teal-700" />
          Capacity-Aware Marketing Intelligence
        </h1>
        <p className="text-xs text-slate-500 mt-0.5">
          Connect marketing demand-generation campaigns directly with plant capacity limits
        </p>
      </div>

      {/* Critical UX Principle Warning Banner */}
      <div className="bg-gradient-to-r from-amber-950 via-amber-900 to-slate-900 text-white p-4 rounded-xl border border-amber-800 flex items-start gap-3 shadow-sm">
        <AlertTriangle className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <div className="text-xs font-bold uppercase tracking-wider text-amber-300">
            Core Operations Rule: High Marketing ROAS ≠ Automatic Spend Increase
          </div>
          <p className="text-xs text-amber-100/90 leading-relaxed">
            If manufacturing plant capacity is constrained, increasing acquisition spend will create unfulfillable demand, leading to wasted marketing budget and customer dissatisfaction.
          </p>
        </div>
      </div>

      {/* Summary KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <StatCard
          title="Total Marketing Spend"
          value={`₹${((marketing_recommendations?.summary?.total_spend_inr || 148000) / 1000).toFixed(0)}k`}
          subtitle="Current Q2 Acquisition Budget"
          icon={<DollarSign className="w-4 h-4 text-teal-700" />}
        />
        <StatCard
          title="Recommended Spend"
          value={`₹${((marketing_recommendations?.summary?.total_recommended_spend_inr || 125000) / 1000).toFixed(0)}k`}
          subtitle="Capacity-Optimized Allocation"
          badgeText="Optimized"
          badgeVariant="teal"
        />
        <StatCard
          title="Constrained Campaigns"
          value={marketing_recommendations?.summary?.constrained_campaigns_count || 3}
          subtitle="Campaigns bottlenecked by plant capacity"
          badgeText="Bottlenecked"
          badgeVariant="warning"
        />
      </div>

      {/* Marketing Action Cards / Table */}
      <Card
        title="Territory Campaign Action Recommendations"
        subtitle="Zero-sum budget reallocation recommendations generated by capacity engine"
      >
        <div className="space-y-4 pt-1">
          {recommendations.map((item, idx) => {
            const isHold = item.action === 'HOLD';
            const isReduce = item.action === 'REDUCE' || item.action === 'REALLOCATE_OUT';
            const isIncrease = item.action === 'INCREASE' || item.action === 'REALLOCATE_IN';

            return (
              <div
                key={idx}
                className="p-4 bg-slate-50 hover:bg-slate-100/70 border border-slate-200/80 rounded-xl space-y-3 transition-colors"
              >
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <h3 className="text-xs font-bold text-slate-900 font-display">
                      {item.region} — {item.channel}
                    </h3>
                    <Badge
                      variant={isReduce ? 'danger' : isHold ? 'warning' : 'success'}
                      size="md"
                    >
                      {item.action.replace('_', ' ')}
                    </Badge>
                  </div>

                  <div className="flex items-center gap-4 text-xs font-semibold">
                    <span className="text-slate-500">
                      ROAS: <strong className="text-slate-900">{item.roas}x</strong>
                    </span>
                    <span className="text-slate-500">
                      Fulfillment: <strong className={item.fulfillment_pct < 60 ? 'text-rose-600' : 'text-teal-700'}>{item.fulfillment_pct.toFixed(1)}%</strong>
                    </span>
                  </div>
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 p-2.5 bg-white border border-slate-200/60 rounded-lg text-xs">
                  <div>
                    <span className="text-slate-400 text-[10px] uppercase font-bold block">Current Spend</span>
                    <span className="font-semibold text-slate-800">₹{item.current_spend_inr.toLocaleString('en-IN')}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 text-[10px] uppercase font-bold block">Recommended</span>
                    <span className="font-bold text-teal-700">₹{item.recommended_spend_inr.toLocaleString('en-IN')}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 text-[10px] uppercase font-bold block">Demand Efficiency</span>
                    <span className="font-semibold text-slate-800">{item.demand_efficiency} kg / ₹1k</span>
                  </div>
                  <div>
                    <span className="text-slate-400 text-[10px] uppercase font-bold block">Budget Change</span>
                    <span className={`font-bold ${item.recommended_spend_inr < item.current_spend_inr ? 'text-rose-600' : 'text-emerald-600'}`}>
                      {item.recommended_spend_inr - item.current_spend_inr === 0
                        ? '₹0'
                        : `₹${(item.recommended_spend_inr - item.current_spend_inr).toLocaleString('en-IN')}`}
                    </span>
                  </div>
                </div>

                <p className="text-xs text-slate-600 leading-relaxed italic bg-slate-100/60 p-2.5 rounded-lg border border-slate-200/50">
                  {item.reason}
                </p>
              </div>
            );
          })}
        </div>
      </Card>
    </div>
  );
};
