import { OperationalPlan, B2BAccount, ScenarioChanges } from '../api/types';

export const DEMO_ORDERS = [
  { date: '2024-05', region: 'Mumbai', channel: 'D2C', revenue_inr: 288000, quantity_kg: 600 },
  { date: '2024-05', region: 'Mumbai', channel: 'B2B', revenue_inr: 320000, quantity_kg: 800, customer_id: 'RetailCo_MUM' },
  { date: '2024-05', region: 'Pune', channel: 'D2C', revenue_inr: 160000, quantity_kg: 350 },
  { date: '2024-05', region: 'Pune', channel: 'B2B', revenue_inr: 220000, quantity_kg: 550, customer_id: 'HotelChain_PUN' },
  { date: '2024-05', region: 'Delhi', channel: 'D2C', revenue_inr: 210000, quantity_kg: 420 },
  { date: '2024-05', region: 'Delhi', channel: 'B2B', revenue_inr: 290000, quantity_kg: 700, customer_id: 'SuperMart_DEL' },
  { date: '2024-05', region: 'Bengaluru', channel: 'D2C', revenue_inr: 195000, quantity_kg: 390 },
  { date: '2024-05', region: 'Bengaluru', channel: 'B2B', revenue_inr: 250000, quantity_kg: 600, customer_id: 'TechCanteen_BLR' },
  { date: '2024-05', region: 'Chennai', channel: 'D2C', revenue_inr: 140000, quantity_kg: 300 },
  { date: '2024-05', region: 'Chennai', channel: 'B2B', revenue_inr: 180000, quantity_kg: 450, customer_id: 'BistroNet_CHE' },
];

export const DEMO_CAPACITY = [
  {
    date: '2024-05',
    internal_capacity_kg: 3500,
    co_manufacturing_capacity_kg: 800,
    downtime_kg: 150,
    reserved_capacity_kg: 200,
    available_capacity_kg: 3950,
  },
];

export const DEMO_MARKETING = [
  { region: 'Mumbai', channel: 'D2C', spend_inr: 45000, attributed_orders: 450, attributed_revenue_inr: 216000 },
  { region: 'Pune', channel: 'D2C', spend_inr: 22000, attributed_orders: 210, attributed_revenue_inr: 98000 },
  { region: 'Delhi', channel: 'D2C', spend_inr: 35000, attributed_orders: 380, attributed_revenue_inr: 180000 },
  { region: 'Bengaluru', channel: 'D2C', spend_inr: 28000, attributed_orders: 290, attributed_revenue_inr: 140000 },
  { region: 'Chennai', channel: 'D2C', spend_inr: 18000, attributed_orders: 170, attributed_revenue_inr: 82000 },
];

export const DEMO_B2B_ACCOUNTS = [
  { customer_name: 'Metro Hypermarket', region: 'Mumbai', monthly_requirement_kg: 800, unit_price_inr: 400, priority: 'HIGH', minimum_fulfillment_pct: 95 },
  { customer_name: 'Apex Food Services', region: 'Pune', monthly_requirement_kg: 550, unit_price_inr: 380, priority: 'HIGH', minimum_fulfillment_pct: 90 },
  { customer_name: 'Capital Caterers', region: 'Delhi', monthly_requirement_kg: 700, unit_price_inr: 410, priority: 'MEDIUM', minimum_fulfillment_pct: 85 },
];

export const DEMO_OPERATIONAL_PLAN: OperationalPlan = {
  target_period: '2024-05',
  strategy: 'balanced',
  risk_mode: 'balanced',
  summary: {
    forecast_demand_kg: 5160,
    d2c_demand_kg: 2060,
    b2b_demand_kg: 3100,
    usable_capacity_kg: 3950,
    shortage_kg: 1210,
    allocated_capacity_kg: 3950,
    unfulfilled_demand_kg: 1210,
    fulfillment_pct: 76.5,
    b2b_fulfillment_pct: 92.4,
    d2c_fulfillment_pct: 52.6,
    utilization_pct: 100.0,
    projected_revenue_inr: 1845000,
    risk_level: 'HIGH',
  },
  capacity_breakdown: {
    total_usable_capacity_kg: 3950,
    total_forecast_demand_kg: 5160,
    shortage_kg: 1210,
    utilization_pct: 100.0,
    internal_capacity_kg: 3500,
    co_manufacturing_capacity_kg: 800,
    downtime_kg: 150,
    reserved_capacity_kg: 200,
    has_shortage: true,
    spare_capacity_kg: 0,
  },
  allocation_plan: {
    strategy: 'balanced',
    available_capacity_kg: 3950,
    total_demand_kg: 5160,
    allocated_capacity_kg: 3950,
    unfulfilled_demand_kg: 1210,
    utilization_pct: 100.0,
    overall_fulfillment_pct: 76.5,
    b2b_fulfillment_pct: 92.4,
    d2c_fulfillment_pct: 52.6,
    total_revenue_inr: 1845000,
    total_b2b_shortfall_kg: 0,
    segments: [
      { segment_id: 'MUM_B2B', region: 'Mumbai', channel: 'B2B', demand_kg: 800, allocated_kg: 800, fulfillment_pct: 100.0, unfulfilled_kg: 0, revenue_inr: 320000 },
      { segment_id: 'MUM_D2C', region: 'Mumbai', channel: 'D2C', demand_kg: 600, allocated_kg: 380, fulfillment_pct: 63.3, unfulfilled_kg: 220, revenue_inr: 182400 },
      { segment_id: 'PUN_B2B', region: 'Pune', channel: 'B2B', demand_kg: 550, allocated_kg: 520, fulfillment_pct: 94.5, unfulfilled_kg: 30, revenue_inr: 197600 },
      { segment_id: 'PUN_D2C', region: 'Pune', channel: 'D2C', demand_kg: 350, allocated_kg: 210, fulfillment_pct: 60.0, unfulfilled_kg: 140, revenue_inr: 96600 },
      { segment_id: 'DEL_B2B', region: 'Delhi', channel: 'B2B', demand_kg: 700, allocated_kg: 700, fulfillment_pct: 100.0, unfulfilled_kg: 0, revenue_inr: 287000 },
      { segment_id: 'DEL_D2C', region: 'Delhi', channel: 'D2C', demand_kg: 420, allocated_kg: 230, fulfillment_pct: 54.8, unfulfilled_kg: 190, revenue_inr: 115000 },
      { segment_id: 'BLR_B2B', region: 'Bengaluru', channel: 'B2B', demand_kg: 600, allocated_kg: 550, fulfillment_pct: 91.7, unfulfilled_kg: 50, revenue_inr: 229160 },
      { segment_id: 'BLR_D2C', region: 'Bengaluru', channel: 'D2C', demand_kg: 390, allocated_kg: 210, fulfillment_pct: 53.8, unfulfilled_kg: 180, revenue_inr: 105000 },
      { segment_id: 'CHE_B2B', region: 'Chennai', channel: 'B2B', demand_kg: 450, allocated_kg: 250, fulfillment_pct: 55.6, unfulfilled_kg: 200, revenue_inr: 100000 },
      { segment_id: 'CHE_D2C', region: 'Chennai', channel: 'D2C', demand_kg: 300, allocated_kg: 100, fulfillment_pct: 33.3, unfulfilled_kg: 200, revenue_inr: 46660 },
    ],
    explanations: [
      'High-priority B2B commitments for Mumbai and Delhi were 100% fulfilled due to strict contractual SLAs.',
      'D2C demand in Chennai was scaled back to protect core regional B2B contracts.',
      'Balanced optimization prioritized higher unit margin segments across all 5 operational regions.',
    ],
  },
  marketing_recommendations: {
    summary: {
      total_spend_inr: 148000,
      total_recommended_spend_inr: 125000,
      constrained_campaigns_count: 3,
    },
    recommendations: [
      {
        region: 'Mumbai',
        channel: 'D2C',
        action: 'HOLD',
        current_spend_inr: 45000,
        recommended_spend_inr: 35000,
        roas: 4.8,
        demand_efficiency: 13.3,
        fulfillment_pct: 63.3,
        reason: 'ROAS is high (4.8x) but Mumbai D2C fulfillment is capped at 63.3%. Reduce acquisition spend until capacity expands.',
      },
      {
        region: 'Pune',
        channel: 'D2C',
        action: 'HOLD',
        current_spend_inr: 22000,
        recommended_spend_inr: 18000,
        roas: 4.4,
        demand_efficiency: 15.9,
        fulfillment_pct: 60.0,
        reason: 'Capacity bottleneck prevents fulfilling additional demand. Hold acquisition campaigns.',
      },
      {
        region: 'Delhi',
        channel: 'D2C',
        action: 'REALLOCATE_OUT',
        current_spend_inr: 35000,
        recommended_spend_inr: 25000,
        roas: 5.1,
        demand_efficiency: 12.0,
        fulfillment_pct: 54.8,
        reason: 'Severe capacity deficit (190 kg unfulfilled). Reallocate ₹10,000 spend to unconstrained regions.',
      },
      {
        region: 'Bengaluru',
        channel: 'D2C',
        action: 'HOLD',
        current_spend_inr: 28000,
        recommended_spend_inr: 25000,
        roas: 5.0,
        demand_efficiency: 13.9,
        fulfillment_pct: 53.8,
        reason: 'Fulfillment is constrained at 53.8%. Keep ad budget stable.',
      },
      {
        region: 'Chennai',
        channel: 'D2C',
        action: 'REDUCE',
        current_spend_inr: 18000,
        recommended_spend_inr: 12000,
        roas: 4.5,
        demand_efficiency: 16.6,
        fulfillment_pct: 33.3,
        reason: 'Chennai faces lowest fulfillment rate (33.3%). Reduce marketing push immediately.',
      },
    ],
  },
  recommendations: [
    {
      action_id: 'ACT_01',
      type: 'ACTIVATE_CO_MANUFACTURING',
      title: 'Activate Co-Manufacturing (+500 kg)',
      description: 'Demand exceeds internal capacity by 1,210 kg. Activate co-manufacturing partner facilities in Western Region to capture ₹320,000 in unfulfilled revenue.',
      priority: 'HIGH',
      estimated_impact: '+₹320,000 Revenue',
      trigger_reason: 'Shortage detected: 1,210 kg deficit across Q2 target period.',
    },
    {
      action_id: 'ACT_02',
      type: 'PROTECT_B2B_COMMITMENT',
      title: 'Protect High-Priority B2B SLAs',
      description: 'Lock in 100% allocation for Metro Hypermarket (Mumbai) and Capital Caterers (Delhi) to prevent penalty shortfalls.',
      priority: 'HIGH',
      estimated_impact: 'Protect ₹607,000 Contract Revenue',
      trigger_reason: 'B2B commitments require minimum 95% fulfillment SLA.',
    },
    {
      action_id: 'ACT_03',
      type: 'REALLOCATE_MARKETING',
      title: 'Reallocate D2C Marketing Spend (-₹23,000)',
      description: 'Pause high-funnel D2C campaigns in Chennai and Delhi where fulfillment is below 55%. Shift budget to capacity expansion.',
      priority: 'MEDIUM',
      estimated_impact: 'Save ₹23,000 Unusable Acquisition Spend',
      trigger_reason: 'High ROAS campaigns generating unfulfillable demand.',
    },
    {
      action_id: 'ACT_04',
      type: 'WAITLIST_D2C',
      title: 'Enable Waitlist for D2C Orders in Chennai',
      description: 'Implement back-order queue for Chennai D2C store to manage customer expectations during peak demand.',
      priority: 'LOW',
      estimated_impact: 'Prevent Customer Churn',
      trigger_reason: 'Chennai D2C fulfillment dropped below 40%.',
    },
  ],
  risk_plan: {
    mode: 'balanced',
    forecast_segments: [
      { region: 'Mumbai', channel: 'B2B', point_forecast_kg: 800, lower_bound_kg: 740, upper_bound_kg: 860, confidence_level: 0.8 },
      { region: 'Mumbai', channel: 'D2C', point_forecast_kg: 600, lower_bound_kg: 540, upper_bound_kg: 670, confidence_level: 0.8 },
      { region: 'Delhi', channel: 'B2B', point_forecast_kg: 700, lower_bound_kg: 650, upper_bound_kg: 760, confidence_level: 0.8 },
      { region: 'Delhi', channel: 'D2C', point_forecast_kg: 420, lower_bound_kg: 380, upper_bound_kg: 470, confidence_level: 0.8 },
    ],
    risk_level: 'HIGH',
    capacity_risk: 'High risk of demand exceeding usable capacity by 1,210 kg. Co-manufacturing expansion recommended.',
  },
};
